# This is a configuration file for the bacon tool
# More info at https://github.com/Canop/bacon

default_job = "check"

[jobs]

[jobs.check]
command = ["cargo", "check", "--color", "always", "--tests"]
need_stdout = false

[jobs.check-lib]
command = ["cargo", "check", "--color", "always", "--tests", "--lib"]
need_stdout = false

[jobs.clippy]
command = ["cargo", "clippy", "--color", "always", "--all"]
need_stdout = false
