[workspace]
allow_dirty = false
changelog_update = true
dependencies_update = true
git_release_enable = false
pr_labels = ["release"]
publish_allow_dirty = false
semver_check = true
publish_timeout = "10m"

[[package]]
name = "swarmd"
changelog_include = ["swarmd_local_runtime", "swarmd_generated", "swarmd_slug-rs", "swarmd_instruments"]
changelog_path = "cli/CHANGELOG.md"
changelog_update = true
git_release_enable = false
publish = true

[[package]]
name = "swarmd_local_runtime"
changelog_update = true
git_release_enable = false
publish = true

[[package]]
name = "swarmd_generated"
changelog_update = true
git_release_enable = false
publish = true

[[package]]
name = "swarmd_slug-rs"
changelog_update = true
git_release_enable = false
publish = true

[[package]]
name = "swarmd_instruments"
changelog_update = true
git_release_enable = false
publish = true
