[target.x86_64-unknown-linux-gnu]
rustflags = []

[target.aarch64-apple-darwin]
rustflags = [ ]

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
[target.i686-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[target.x86_64-unknown-linux-musl]
rustflags = [
  "-C", "target-feature=+crt-static",
  "-C", "link-self-contained=yes",
]

[term]
verbose = false
color = 'auto'
