/*
 * Swarmd Backend API Documentation for swarmd_api version 0.1.0
 *
 * # Introduction  blblbllb
 *
 * The version of the OpenAPI document:
 * Contact: anthony@brevz.io
 * Generated by: https://openapi-generator.tech
 */

/// AppError : A default error response for most API errors.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppError {
    /// An error message.
    #[serde(rename = "error")]
    pub error: String,
    /// A unique error ID.
    #[serde(rename = "trace_id")]
    pub trace_id: i32,
}

impl AppError {
    /// A default error response for most API errors.
    pub fn new(error: String, trace_id: i32) -> AppError {
        AppError { error, trace_id }
    }
}
