/*
 * Swarmd Backend API Documentation for swarmd_api version 0.1.0
 *
 * # Introduction  blblbllb 
 *
 * The version of the OpenAPI document: 
 * Contact: anthony@brevz.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateProjectParams {
    #[serde(rename = "organization_id")]
    pub organization_id: String,
}

impl CreateProjectParams {
    pub fn new(organization_id: String) -> CreateProjectParams {
        CreateProjectParams {
            organization_id,
        }
    }
}


