/*
 * Swarmd Backend API Documentation for swarmd_api version 0.1.0
 *
 * # Introduction  blblbllb
 *
 * The version of the OpenAPI document:
 * Contact: anthony@brevz.io
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateProjectPayload {
    #[serde(rename = "slug")]
    pub slug: String,
}

impl CreateProjectPayload {
    pub fn new(slug: String) -> CreateProjectPayload {
        CreateProjectPayload { slug }
    }
}
