/*
 * Swarmd Backend API Documentation for swarmd_api version 0.1.0
 *
 * # Introduction  blblbllb 
 *
 * The version of the OpenAPI document: 
 * Contact: anthony@brevz.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListProjectResponse {
    #[serde(rename = "projects")]
    pub projects: Vec<crate::models::Project>,
}

impl ListProjectResponse {
    pub fn new(projects: Vec<crate::models::Project>) -> ListProjectResponse {
        ListProjectResponse {
            projects,
        }
    }
}


