/*
 * Swarmd Backend API Documentation for swarmd_api version 0.1.0
 *
 * # Introduction  blblbllb 
 *
 * The version of the OpenAPI document: 
 * Contact: anthony@brevz.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListOrganisationResponse {
    #[serde(rename = "organisations")]
    pub organisations: Vec<crate::models::PartialOrganisation>,
}

impl ListOrganisationResponse {
    pub fn new(organisations: Vec<crate::models::PartialOrganisation>) -> ListOrganisationResponse {
        ListOrganisationResponse {
            organisations,
        }
    }
}


