/*
 * Swarmd Backend API Documentation for swarmd_api version 0.1.0
 *
 * # Introduction  blblbllb
 *
 * The version of the OpenAPI document:
 * Contact: anthony@brevz.io
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublishWorkerResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "route")]
    pub route: Option<String>,
}

impl PublishWorkerResponse {
    pub fn new(id: String, route: Option<String>) -> PublishWorkerResponse {
        PublishWorkerResponse { id, route }
    }
}
