/*
 * Swarmd Backend API Documentation for swarmd_api version 0.1.0
 *
 * # Introduction  blblbllb 
 *
 * The version of the OpenAPI document: 
 * Contact: anthony@brevz.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublishWorkerPayload {
    #[serde(rename = "worker_id")]
    pub worker_id: String,
}

impl PublishWorkerPayload {
    pub fn new(worker_id: String) -> PublishWorkerPayload {
        PublishWorkerPayload {
            worker_id,
        }
    }
}


