/*
 * Swarmd Backend API Documentation for swarmd_api version 0.1.0
 *
 * # Introduction  blblbllb 
 *
 * The version of the OpenAPI document: 
 * Contact: anthony@brevz.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UploadWorkerParams {
    #[serde(rename = "organization_id")]
    pub organization_id: String,
    #[serde(rename = "project_id")]
    pub project_id: String,
}

impl UploadWorkerParams {
    pub fn new(organization_id: String, project_id: String) -> UploadWorkerParams {
        UploadWorkerParams {
            organization_id,
            project_id,
        }
    }
}


